name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

  ## Download
  - [Firmware Binary](https://github.com/Gfermoto/soil-sensor-7in1/releases/download/v$RESOLVED_VERSION/jxct-soil-sensor-v$RESOLVED_VERSION.bin)
  - [Source Code (ZIP)](https://github.com/Gfermoto/soil-sensor-7in1/archive/v$RESOLVED_VERSION.zip)
  - [Source Code (TAR.GZ)](https://github.com/Gfermoto/soil-sensor-7in1/archive/v$RESOLVED_VERSION.tar.gz)

  ## Installation
  1. Download the firmware binary
  2. Use ESP32 Flash Download Tool or esptool.py
  3. Flash to your ESP32 device
  4. Configure WiFi and sensor settings via web interface

  ## Changelog
  $CHANGES

  ## Technical Details
  - **Version:** $RESOLVED_VERSION
  - **Build Date:** $BUILD_DATE
  - **ESP32 Framework:** Arduino ESP32 3.20017
  - **C++ Standard:** C++17
  - **Flash Size:** ~1MB
  - **RAM Usage:** ~58KB

  ## Support
  - 📖 [Documentation](https://github.com/Gfermoto/soil-sensor-7in1/tree/main/docs)
  - 🐛 [Report Issues](https://github.com/Gfermoto/soil-sensor-7in1/issues)
  - 💬 [Discussions](https://github.com/Gfermoto/soil-sensor-7in1/discussions)

  ---
  *This release was automatically generated by [Release Drafter](https://github.com/release-drafter/release-drafter)* 