name: Build & Release Firmware

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python & PlatformIO
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install PlatformIO CLI
        run: pip install --upgrade platformio

      - name: Verify VERSION file matches tag
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          FILE_VERSION=$(cat VERSION)
          if [ "$TAG_VERSION" != "$FILE_VERSION" ]; then
            echo "❌ VERSION file ($FILE_VERSION) doesn't match tag ($TAG_VERSION)"
            echo "This should not happen if release_cycle.py worked correctly"
            exit 1
          else
            echo "✅ VERSION file matches tag: $TAG_VERSION"
          fi

      - name: Build firmware (production)
        run: pio run -e esp32dev-production

      - name: Prepare artifacts (firmware.bin & manifest.json)
        shell: bash
        run: |
          mkdir dist
          cp .pio/build/esp32dev-production/firmware.bin dist/
          HASH=$(sha256sum dist/firmware.bin | cut -d ' ' -f1)
          VERSION=${GITHUB_REF_NAME#v}
          cat > dist/manifest.json <<EOF
          {
            "version": "${VERSION}",
            "url": "https://github.com/Gfermoto/soil-sensor-7in1/releases/download/${GITHUB_REF_NAME}/firmware.bin",
            "sha256": "${HASH}"
          }
          EOF
          echo "SHA256: $HASH"

      - name: Create GitHub Release & upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/firmware.bin
            dist/manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 