import argparse
import os
import re
from pathlib import Path

HEADER = """<!-- autogenerated - CI -->\n# 📑 Сводка автоматических отчётов\n"""

TABLE_HEAD = """\n| Отчёт | Размер | Метрика | Значение |\n|-------|--------|---------|----------|\n"""

def size_fmt(num: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if num < 1024.0:
            return f"{num:.1f}{unit}"
        num /= 1024.0
    return f"{num:.1f}TB"


def count_clang_tidy(path: Path) -> int:
    cnt = 0
    with path.open(encoding="utf-8", errors="ignore") as f:
        for line in f:
            if "DiagnosticName:" in line:
                cnt += 1
    return cnt


def count_iwyu(path: Path) -> int:
    cnt = 0
    with path.open(encoding="utf-8", errors="ignore") as f:
        for line in f:
            if line.startswith("["):
                cnt += 1
    return cnt


def count_lizard(path: Path) -> int:
    cnt = 0
    regex = re.compile(r"\s+(\d+)\s+\S+\s+\S+\s+\S+")
    with path.open(encoding="utf-8", errors="ignore") as f:
        for line in f:
            m = regex.match(line)
            if m:
                try:
                    ccn = int(m.group(1))
                    if ccn > 15:
                        cnt += 1
                except ValueError:
                    pass
    return cnt


def count_cloc_dup(path: Path) -> int:
    cnt = 0
    with path.open(encoding="utf-8", errors="ignore") as f:
        for line in f:
            if "DUPE" in line:
                cnt += 1
    return cnt


COUNT_MAP = {
    "clang_tidy_fixes_auto.yaml": ("Diagnostics", count_clang_tidy),
    "iwyu_report_auto.txt": ("IWYU suggestions", count_iwyu),
    "lizard_report_auto.txt": ("CCN>15", count_lizard),
    "cloc_dup_auto.txt": ("Duplicate groups", count_cloc_dup),
}

def build_summary(directory: Path) -> str:
    lines = [HEADER, TABLE_HEAD]
    for file in sorted(directory.glob("*_auto.*")):
        size = size_fmt(file.stat().st_size)
        base = file.name
        metric, func = COUNT_MAP.get(base, ("—", None))
        value = "—"
        if func is not None:
            try:
                value = str(func(file))
            except Exception:
                value = "err"
        lines.append(f"| {base} | {size} | {metric} | {value} |\n")
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate markdown summary of auto reports")
    parser.add_argument("--in-dir", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    in_dir = Path(args.in_dir)
    out_file = Path(args.out)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    md = build_summary(in_dir)
    out_file.write_text(md, encoding="utf-8")

if __name__ == "__main__":
    main() 