#!/usr/bin/env python3
"""
JXCT Release Manager - автоматическое управление версиями и релизами
Единственный скрипт для всех операций с версиями и релизами.
"""

import os
import re
import sys
import subprocess
import argparse
from datetime import datetime, timezone
from pathlib import Path

class ReleaseManager:
    def __init__(self, project_dir=None):
        self.project_dir = Path(project_dir) if project_dir else Path.cwd()
        self.version_file = self.project_dir / "VERSION"
        self.version_header = self.project_dir / "include" / "version.h"
        self.platformio_ini = self.project_dir / "platformio.ini"

    def get_current_version(self) -> str:
        """Получить текущую версию из файла VERSION"""
        if not self.version_file.exists():
            return "0.0.0"
        return self.version_file.read_text(encoding='utf-8').strip()

    def get_latest_git_tag(self) -> str:
        """Получить последний git тег"""
        try:
            result = subprocess.run(
                ["git", "describe", "--tags", "--abbrev=0"],
                cwd=self.project_dir,
                capture_output=True,
                text=True,
                check=True
            )
            tag = result.stdout.strip()
            return tag.lstrip("v") if tag.startswith("v") else tag
        except subprocess.CalledProcessError:
            return ""

    def validate_version_format(self, version: str) -> bool:
        """Проверить формат версии (major.minor.patch)"""
        return bool(re.match(r"^\d+\.\d+\.\d+$", version))

    def parse_version(self, version: str) -> tuple:
        """Разобрать версию на компоненты"""
        match = re.match(r"(\d+)\.(\d+)\.(\d+)", version)
        if not match:
            raise ValueError(f"Неверный формат версии: {version}")
        return tuple(map(int, match.groups()))

    def update_version_file(self, version: str):
        """Обновить файл VERSION"""
        self.version_file.write_text(f"{version}\n", encoding='utf-8')
        print(f"✅ Обновлен файл VERSION: {version}")

    def update_version_header(self, version: str):
        """Обновить include/version.h"""
        major, minor, patch = self.parse_version(version)

        header_content = f"""#pragma once

// Auto-generated. DO NOT EDIT MANUALLY.
// Generated by scripts/release_manager.py at {datetime.now(timezone.utc).isoformat()}Z

#define JXCT_VERSION_MAJOR {major}
#define JXCT_VERSION_MINOR {minor}
#define JXCT_VERSION_PATCH {patch}

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define JXCT_VERSION_STRING TOSTRING(JXCT_VERSION_MAJOR) "." TOSTRING(JXCT_VERSION_MINOR) "." TOSTRING(JXCT_VERSION_PATCH)

static const char DEVICE_MANUFACTURER[] = "Eyera";
static const char DEVICE_MODEL[] = "JXCT-7in1";
static const char DEVICE_SW_VERSION[] = JXCT_VERSION_STRING;
static const char* FIRMWARE_VERSION = JXCT_VERSION_STRING;

#define JXCT_VERSION_CODE (JXCT_VERSION_MAJOR * 10000 + JXCT_VERSION_MINOR * 100 + JXCT_VERSION_PATCH)
#define JXCT_VERSION_AT_LEAST(major, minor, patch)     (JXCT_VERSION_CODE >= ((major) * 10000 + (minor) * 100 + (patch)))

#ifndef JXCT_BUILD_DATE
#define JXCT_BUILD_DATE __DATE__
#endif
#ifndef JXCT_BUILD_TIME
#define JXCT_BUILD_TIME __TIME__
#endif
#define JXCT_FULL_VERSION_STRING JXCT_VERSION_STRING " (built " JXCT_BUILD_DATE " " JXCT_BUILD_TIME ")"
"""

        self.version_header.parent.mkdir(parents=True, exist_ok=True)
        self.version_header.write_text(header_content, encoding='utf-8')
        print(f"✅ Обновлен include/version.h: {version}")

    def update_platformio_ini(self, version: str):
        """Обновить версию в platformio.ini"""
        if not self.platformio_ini.exists():
            print("⚠️  platformio.ini не найден, пропускаем")
            return

        try:
            content = self.platformio_ini.read_text(encoding='utf-8')
        except UnicodeDecodeError:
            # Пробуем другие кодировки
            for encoding in ['cp1251', 'latin-1', 'iso-8859-1']:
                try:
                    content = self.platformio_ini.read_text(encoding=encoding)
                    break
                except UnicodeDecodeError:
                    continue
            else:
                print("❌ Не удалось прочитать platformio.ini")
                return

        # Обновляем комментарий с версией
        content = re.sub(
            r"; Version: \d+\.\d+\.\d+",
            f"; Version: {version}",
            content
        )

        # Обновляем дату последнего обновления
        current_date = datetime.now().strftime("%B %Y")
        content = re.sub(
            r"; Last Updated: [A-Za-z]+ \d{4}",
            f"; Last Updated: {current_date}",
            content
        )

        self.platformio_ini.write_text(content, encoding='utf-8')
        print(f"✅ Обновлен platformio.ini: {version}")

    def bump_version(self, bump_type: str):
        """Увеличить версию (major, minor, patch)"""
        current = self.get_current_version()
        major, minor, patch = self.parse_version(current)

        if bump_type == "major":
            major += 1
            minor = 0
            patch = 0
        elif bump_type == "minor":
            minor += 1
            patch = 0
        elif bump_type == "patch":
            patch += 1
        else:
            raise ValueError(f"Неизвестный тип bump: {bump_type}")

        new_version = f"{major}.{minor}.{patch}"
        return new_version

    def update_all_version_files(self, version: str):
        """Обновить версию во всех файлах"""
        print(f"📝 Обновление версии до {version}...")
        self.update_version_file(version)
        self.update_version_header(version)
        self.update_platformio_ini(version)
        print(f"✅ Версия {version} обновлена во всех файлах")

    def delete_git_tag(self, version: str):
        """Удалить git тег локально и на origin"""
        tag_name = f"v{version}"
        try:
            subprocess.run(["git", "tag", "-d", tag_name], cwd=self.project_dir, check=True)
            subprocess.run(["git", "push", "origin", f":refs/tags/{tag_name}"], cwd=self.project_dir, check=True)
            print(f"🗑️  Удалён старый тег: {tag_name}")
        except subprocess.CalledProcessError:
            print(f"⚠️  Не удалось удалить тег {tag_name} (возможно, не существует)")

    def create_git_tag(self, version: str, message: str = None, force: bool = False):
        """Создать git тег, при force удалить старый"""
        tag_name = f"v{version}"
        # Проверяем, существует ли тег
        exists = False
        try:
            subprocess.run(["git", "rev-parse", tag_name], cwd=self.project_dir, check=True, capture_output=True)
            exists = True
        except subprocess.CalledProcessError:
            pass
        if exists:
            if force:
                self.delete_git_tag(version)
            else:
                print(f"⚠️  Тег {tag_name} уже существует")
                return False
        # Создаем тег
        tag_message = message or f"JXCT Soil Sensor v{version}: релиз"
        subprocess.run(["git", "tag", "-a", tag_name, "-m", tag_message], cwd=self.project_dir, check=True)
        print(f"✅ Создан git тег: {tag_name}")
        return True

    def commit_changes(self, version: str, message: str = None):
        """Закоммитить изменения версии"""
        try:
            subprocess.run(
                ["git", "add", "VERSION", "include/version.h", "platformio.ini"],
                cwd=self.project_dir,
                check=True
            )

            commit_msg = message or f"version: обновлена до {version}"
            subprocess.run(
                ["git", "commit", "-m", commit_msg],
                cwd=self.project_dir,
                check=True
            )
            print(f"✅ Изменения закоммичены: {version}")
            return True
        except subprocess.CalledProcessError as e:
            print(f"❌ Ошибка при коммите: {e}")
            return False

    def push_changes(self, push_tag: bool = True):
        """Запушить изменения и тег"""
        try:
            # Пушим изменения
            subprocess.run(
                ["git", "push", "origin", "main"],
                cwd=self.project_dir,
                check=True
            )
            print("✅ Изменения запушены в main")

            # Пушим тег
            if push_tag:
                subprocess.run(
                    ["git", "push", "origin", "--tags"],
                    cwd=self.project_dir,
                    check=True
                )
                print("✅ Теги запушены")
            return True
        except subprocess.CalledProcessError as e:
            print(f"❌ Ошибка при пуше: {e}")
            return False

    def create_release(self, version: str, message: str = None, auto_push: bool = True, force_tag: bool = False, no_bump: bool = False):
        """Создать полный релиз, с опциями force_tag и no_bump"""
        print(f"🚀 Создание релиза {version}... (force_tag={force_tag}, no_bump={no_bump})")
        if not self.validate_version_format(version):
            print(f"❌ Неверный формат версии: {version}")
            return False
        if not no_bump:
            self.update_all_version_files(version)
            if not self.commit_changes(version, f"release: версия {version} — автоматическое обновление"):
                return False
        # Создаём тег (force_tag)
        if not self.create_git_tag(version, message, force=force_tag):
            return False
        if auto_push:
            if not self.push_changes():
                return False
        print(f"🎉 Релиз {version} успешно создан!")
        return True

    def sync_versions(self):
        """Синхронизировать версии между файлами"""
        print("🔄 Синхронизация версий...")

        # Получаем версию из git тега или файла VERSION
        git_version = self.get_latest_git_tag()
        file_version = self.get_current_version()

        if git_version and file_version != git_version:
            print(f"📝 Синхронизируем версию: {file_version} → {git_version}")
            self.update_all_version_files(git_version)
            return True
        elif not git_version:
            print(f"📝 Используем версию из файла: {file_version}")
            self.update_version_header(file_version)
            self.update_platformio_ini(file_version)
            return True

        print("✅ Версии уже синхронизированы")
        return False

def main():
    parser = argparse.ArgumentParser(description="JXCT Release Manager - управление версиями и релизами")
    parser.add_argument("command", choices=["version", "release", "bump", "sync"], help="Команда для выполнения")
    parser.add_argument("--version", "-v", help="Версия для релиза (например, 3.6.2)")
    parser.add_argument("--type", "-t", choices=["major", "minor", "patch"], help="Тип увеличения версии для bump/version")
    parser.add_argument("--message", "-m", help="Сообщение для коммита/тега")
    parser.add_argument("--no-push", action="store_true", help="Не пушить изменения автоматически")
    parser.add_argument("--no-commit", action="store_true", help="Не создавать коммит (только обновить файлы)")
    parser.add_argument("--project-dir", help="Директория проекта")
    parser.add_argument("--force-tag", action="store_true", help="Пересоздать тег, если уже существует")
    parser.add_argument("--no-bump", action="store_true", help="Не обновлять файлы версии, только тег и пуш")
    args = parser.parse_args()
    manager = ReleaseManager(args.project_dir)
    try:
        if args.command == "version":
            if not args.type:
                print("❌ Для команды version требуется указать --type")
                sys.exit(1)
            new_version = manager.bump_version(args.type)
            print(f"📈 Новая версия: {new_version}")
            manager.update_all_version_files(new_version)
            if not args.no_commit:
                if not manager.commit_changes(new_version, args.message):
                    sys.exit(1)
                if not args.no_push:
                    if not manager.push_changes(push_tag=False):
                        sys.exit(1)
            print(f"✅ Версия {new_version} успешно обновлена!")
        elif args.command == "release":
            if not args.version:
                print("❌ Для команды release требуется указать --version")
                sys.exit(1)
            success = manager.create_release(args.version, args.message, not args.no_push, force_tag=args.force_tag, no_bump=args.no_bump)
            sys.exit(0 if success else 1)
        elif args.command == "bump":
            if not args.type:
                print("❌ Для команды bump требуется указать --type")
                sys.exit(1)
            new_version = manager.bump_version(args.type)
            print(f"📈 Новая версия: {new_version}")
            success = manager.create_release(new_version, args.message, not args.no_push)
            sys.exit(0 if success else 1)
        elif args.command == "sync":
            changed = manager.sync_versions()
            if changed:
                print("💡 Выполните git add и git commit для сохранения изменений")
            sys.exit(0)
    except Exception as e:
        print(f"❌ Ошибка: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
