name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build firmware (development)
        uses: docker://ghcr.io/gfermoto/soil-sensor-7in1:main
        with:
          args: pio run -e esp32dev
          
      - name: Build firmware (production)
        uses: docker://ghcr.io/gfermoto/soil-sensor-7in1:main
        with:
          args: pio run -e esp32dev-production
          
      - name: Run unit tests (native)
        uses: docker://ghcr.io/gfermoto/soil-sensor-7in1:main
        with:
          args: pio test -e native -vv
        continue-on-error: true
          
      - name: Route presence tests
        uses: docker://ghcr.io/gfermoto/soil-sensor-7in1:main
        with:
          args: python -m unittest discover -s test -p "test_routes.py"
        continue-on-error: true

      - name: Static analysis with clang-tidy
        uses: docker://ghcr.io/gfermoto/soil-sensor-7in1:main
        with:
          args: bash scripts/static_analysis.sh
        continue-on-error: true

      - name: Technical debt analysis
        uses: docker://ghcr.io/gfermoto/soil-sensor-7in1:main
        with:
          args: python scripts/analyze_technical_debt.py
        continue-on-error: true 