name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build firmware (release)
        run: |
          platformio run -e release

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware-bin
          path: .pio/build/release/firmware.bin

      - name: Install clang & cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy cppcheck

      - name: clang-format style check
        run: |
          bash -c 'FILES=$(git ls-files "*.cpp" "*.h");
          for f in $FILES; do clang-format -style=file --dry-run --Werror "$f"; done'

      - name: clang-tidy (warnings only)
        run: |
          bash -c 'clang-tidy -p . $(git ls-files "*.cpp") || true'

      - name: cppcheck static analysis
        run: |
          cppcheck --project compile_commands.json --enable=warning,style,performance --inline-suppr --quiet --output-file=cppcheck.txt || true

      - name: Upload static analysis report
        uses: actions/upload-artifact@v3
        with:
          name: static-analysis
          path: |
            cppcheck.txt 