name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Пропускаем CI если коммит от GitHub Actions (релизы)
    if: github.actor != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Docker image
        uses: docker://ghcr.io/gfermoto/soil-sensor-7in1:main
        with:
          args: pio run -e esp32dev -e esp32dev-production
          
      - name: Run unit tests (native)
        uses: docker://ghcr.io/gfermoto/soil-sensor-7in1:main
        with:
          args: pio test -e native -vv
          
      - name: Route presence tests
        uses: docker://ghcr.io/gfermoto/soil-sensor-7in1:main
        with:
          args: python -m unittest discover -s test -p "test_routes.py"

      # конец job 