name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          
      - name: Build firmware (development)
        run: pio run -e esp32dev
        continue-on-error: true
          
      - name: Build firmware (production)
        run: pio run -e esp32dev-production
        continue-on-error: true
          
      - name: Run unit tests (native)
        run: pio test -e native -vv
        continue-on-error: true  # Не блокируем CI если native тесты падают
          
      - name: Route presence tests
        run: python -m unittest discover -s test -p "test_routes.py"
        continue-on-error: true

      - name: Static analysis with clang-tidy
        run: bash scripts/static_analysis.sh
        continue-on-error: true  # Не блокируем CI если статический анализ падает

      - name: Technical debt analysis
        run: python scripts/analyze_technical_debt.py
        continue-on-error: true  # Не блокируем CI если анализ технического долга падает

      # конец job 