name: Doc Audit

on:
  pull_request:
    paths:
      - "**/*.md"
      - "VERSION"
      - "include/version.h"
      - "platformio.ini"
      - "scripts/doc_consistency_check.py"
  push:
    branches: [ main ]
    paths:
      - "**/*.md"
      - "VERSION"
      - "include/version.h"
      - "platformio.ini"
      - "scripts/doc_consistency_check.py"
  schedule:
    - cron: '0 3 * * 0'  # еженедельно по воскресеньям 03:00 UTC

jobs:
  doc-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run doc consistency check
        run: python scripts/doc_consistency_check.py --verbose
      - name: Markdown lint (non-blocking)
        continue-on-error: true  # лишь предупреждение
        run: |
          npm install -g markdownlint-cli@0.37.0
          markdownlint "**/*.md" "!docs/html/**" "!site/**" 