name: Docs CI

on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Lint markdown
        continue-on-error: true
        run: markdownlint "**/*.md" --config .markdownlint.yml

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install link checker
        run: npm install -g markdown-link-check
      - name: Check links (changed files only)
        continue-on-error: true
        run: |
          git fetch --depth=2 origin "$GITHUB_REF"
          files=$(git diff --name-only HEAD^ HEAD -- '*.md')
          if [ -z "$files" ]; then
            echo "No markdown files changed; skipping link check."
            exit 0
          fi
          for f in $files; do
            echo "▶ checking $f";
            markdown-link-check -q "$f";
          done 