name: Docs CI

on:
  pull_request:
    paths:
      - '**.md'
      - '**.h'
      - '**.cpp'
      - Doxyfile
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.h'
      - '**.cpp'
      - Doxyfile

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Lint markdown
        continue-on-error: true
        run: markdownlint "**/*.md" --config .markdownlint.yml

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install link checker
        run: npm install -g markdown-link-check
      - name: Check links (changed files only)
        continue-on-error: true
        run: |
          git fetch --depth=2 origin "$GITHUB_REF"
          files=$(git diff --name-only HEAD^ HEAD -- '*.md')
          if [ -z "$files" ]; then
            echo "No markdown files changed; skipping link check."
            exit 0
          fi
          for f in $files; do
            echo "▶ checking $f";
            markdown-link-check -q "$f";
          done

  api-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli
      - name: Validate OpenAPI spec
        run: swagger-cli validate docs/api/openapi.yaml

  doxygen-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Doxygen & Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - name: Generate Doxygen HTML
        run: doxygen Doxyfile
      - name: Commit updated HTML (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain docs_src/_doxygen/html)" ]; then
            git add docs_src/_doxygen/html
            git commit -m "docs(auto): regenerate Doxygen HTML" || echo "Nothing to commit"
            git push origin ${GITHUB_REF}
          fi
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-html
          path: docs/html 