name: Force Update GitHub Pages

on:
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Принудительное обновление'
        required: true
        default: 'true'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  force-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Doxygen documentation
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          doxygen Doxyfile

      - name: Build MkDocs site
        run: |
          mkdocs build --site-dir site --verbose

      - name: Force cache busting
        run: |
          # Создаем уникальный файл для принудительного обновления
          echo "<!-- FORCE UPDATE: $(date +%Y%m%d_%H%M%S) -->" > site/force-update.html
          echo "<!-- GIT HASH: $(git rev-parse HEAD) -->" >> site/force-update.html
          echo "<!-- TIMESTAMP: $(date +%s) -->" >> site/force-update.html
          
          # Добавляем кэш-бюстинг в главную страницу
          sed -i 's|</head>|<!-- CACHE BUST: $(date +%s) -->\n</head>|' site/index.html

      - name: Create .nojekyll file
        run: |
          touch site/.nojekyll
          echo "GitHub Pages без Jekyll - $(date)" > site/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 