name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**.md'
      - 'Doxyfile'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug repository structure
        run: |
          echo "=== Repository structure ==="
          ls -la
          echo "=== Source files ==="
          find src -name "*.cpp" -o -name "*.h" | head -10
          echo "=== Include files ==="
          find include -name "*.h" | head -10
          echo "=== Documentation files ==="
          find docs -name "*.md" | head -10
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g markdownlint-cli
          npm install -g markdown-link-check
          npm install -g markdown-it
          npm install -g markdown-it-html5-embed
          
      - name: Lint markdown
        run: |
          echo "=== Linting markdown files ==="
          if [ -f ".markdownlint.yml" ]; then
            markdownlint "**/*.md" --config .markdownlint.yml || echo "Markdown linting completed with warnings"
          else
            markdownlint "**/*.md" || echo "Markdown linting completed with warnings"
          fi
        
      - name: Check links
        run: |
          echo "=== Checking markdown links ==="
          files=$(git ls-files '*.md')
          for f in $files; do 
            if [ -f "$f" ]; then
              echo "Checking links in: $f"
              markdown-link-check -q "$f" || echo "Link check failed for $f, continuing..."
            fi
          done
          
      - name: Install Doxygen
        run: |
          echo "=== Installing Doxygen ==="
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          doxygen --version
          
      - name: Generate documentation
        run: |
          echo "=== Generating Doxygen documentation ==="
          if [ -f "Doxyfile" ]; then
            echo "Doxyfile found, generating documentation..."
            doxygen Doxyfile
            echo "Doxygen generation completed"
            
            if [ -d "docs/html" ]; then
              echo "✅ docs/html directory created successfully"
              echo "=== Contents of docs/html ==="
              ls -la docs/html/
              echo "=== Number of files generated ==="
              find docs/html -type f | wc -l
            else
              echo "❌ docs/html directory not found after Doxygen generation"
              echo "Creating fallback structure..."
              mkdir -p docs/html
            fi
          else
            echo "❌ Doxyfile not found, creating basic documentation structure"
            mkdir -p docs/html
          fi
          
      - name: Create main page
        run: |
          echo "=== Creating main page ==="
          if [ ! -d "docs/html" ]; then
            mkdir -p docs/html
          fi
          
          # Копируем готовый HTML файл
          if [ -f "docs/html/index.html" ]; then
            echo "✅ Using existing docs/html/index.html"
          else
            echo "❌ docs/html/index.html not found, creating basic fallback"
            echo "<!DOCTYPE html><html><head><title>JXCT 7-в-1</title></head><body><h1>🌱 JXCT 7-в-1 Датчик Почвы</h1><p>Документация</p></body></html>" > docs/html/index.html
          fi
          
          echo "✅ Main page ready"
          
      - name: Verify documentation structure
        run: |
          echo "=== Verifying documentation structure ==="
          echo "Checking docs/html directory structure:"
          ls -la docs/html/
          if [ -f "docs/html/index.html" ]; then
            echo "✅ Main page exists"
          else
            echo "❌ Main page not found"
            exit 1
          fi
          
          echo "=== Final structure ==="
          find docs/html -type f | head -20
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/html'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 