name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: "${{ github.workspace }}"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          
      - name: Check mkdocs configuration
        run: |
          echo "=== Checking mkdocs.yml ==="
          cat mkdocs.yml
          echo "=== Checking docs structure ==="
          ls -la docs/
          
      - name: Generate Doxygen docs
        run: |
          echo "=== Generating Doxygen documentation ==="
          doxygen Doxyfile
          echo "=== Doxygen output ==="
          ls -la docs/doxygen/html/ || echo "Doxygen failed, continuing..."

      - name: Build MkDocs site
        run: |
          echo "=== Building MkDocs site ==="
          mkdocs build --verbose
          echo "=== Site structure ==="
          ls -la site/
          echo "=== Checking if pages were generated ==="
          find site/ -name "*.html" | head -10

      - name: Copy Doxygen HTML to site/api
        run: |
          echo "=== Copying Doxygen to site/api ==="
          mkdir -p site/api
          if [ -d "docs/doxygen/html" ]; then
            cp -r docs/doxygen/html/* site/api/
            echo "=== API directory contents ==="
            ls -la site/api/
          else
            echo "Doxygen directory not found, creating placeholder"
            echo "<html><body><h1>API Documentation</h1><p>Doxygen documentation will be generated here.</p></body></html>" > site/api/index.html
          fi

      - name: Add .nojekyll
        run: touch site/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Verify deployment
        run: |
          echo "=== Deployment verification ==="
          echo "Page URL: ${{ steps.deployment.outputs.page_url }}"
          echo "✅ GitHub Pages deployment completed!" 