name: Publish Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REPO_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/gfermoto/soil-sensor-7in1:main
          ghcr.io/gfermoto/soil-sensor-7in1:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 
        
    - name: Test Docker image
      run: |
        echo "Testing Docker image functionality..."
        docker run --rm ghcr.io/gfermoto/soil-sensor-7in1:main python3 --version
        docker run --rm ghcr.io/gfermoto/soil-sensor-7in1:main pio --version
        docker run --rm ghcr.io/gfermoto/soil-sensor-7in1:main clang-tidy --version
        echo "✅ Docker image test completed successfully!" 