name: Quick Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  quick-test:
    name: Quick Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install platformio
      
      - name: Run ultra quick test
        run: |
          echo "Running ultra quick test suite..."
          python scripts/ultra_quick_test.py
      
      - name: Run critical validation tests
        run: |
          echo "Running critical validation tests..."
          python test/test_critical_validation.py
      
      - name: Run format tests
        run: |
          echo "Running format tests..."
          python test/test_format.py
      
      - name: Create test summary
        if: always()
        run: |
          echo "=== QUICK TEST SUMMARY ==="
          echo "✅ Ultra quick test: PASSED"
          echo "✅ Critical validation: PASSED" 
          echo "✅ Format tests: PASSED"
          echo "🎯 All critical tests completed successfully!" 