name: Update Repository Info

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-repo-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get version from file
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Если это тег, берём версию из тега
            VERSION=${GITHUB_REF#refs/tags/}
            VERSION_CLEAN=${VERSION#v}
          else
            # Если это main, берём версию из файла VERSION
            VERSION_CLEAN=$(cat VERSION)
          fi
          echo "version_clean=${VERSION_CLEAN}" >> $GITHUB_OUTPUT
          
      - name: Update repository description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = '${{ steps.version.outputs.version_clean }}';
            const description = `🌱 JXCT 7-в-1 Датчик Почвы (v${version}) - Профессиональная IoT система мониторинга почвы на базе ESP32 с Modbus RTU, MQTT и продвинутыми алгоритмами компенсации`;
            
            await github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              description: description,
              homepage: 'https://gfermoto.github.io/soil-sensor-7in1/',
              topics: ['esp32', 'iot', 'soil-sensor', 'modbus', 'mqtt', 'arduino', 'platformio', 'agpl-3.0']
            });
            
            console.log(`Repository description updated to: ${description}`); 