name: 🔄 Update Site Reports

on:
  # Запуск после завершения тестирования
  workflow_run:
    workflows: ["🧪 Comprehensive Testing"]
    types:
      - completed
  
  # Ручной запуск
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Принудительное обновление отчётов'
        required: false
        default: false
        type: boolean
  
  # Ежедневное обновление в 3:00 UTC
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-reports:
    name: 📊 Обновить отчёты на сайте
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 🔍 Check for test reports
        id: check_reports
        run: |
          if [ -f "test_reports/simple-test-report.json" ] && [ -f "test_reports/technical-debt.json" ]; then
            echo "reports_exist=true" >> $GITHUB_OUTPUT
            echo "✅ Найдены отчёты тестирования"
          else
            echo "reports_exist=false" >> $GITHUB_OUTPUT
            echo "⚠️ Отчёты тестирования не найдены"
          fi
      
      - name: 🧪 Generate reports if missing
        if: steps.check_reports.outputs.reports_exist == 'false' || github.event.inputs.force_update == 'true'
        run: |
          echo "🔄 Генерируем отчёты..."
          python scripts/run_comprehensive_tests.py --type basic --reports-only
      
      - name: 🔄 Synchronize reports to site
        run: |
          echo "🔄 Синхронизируем отчёты с сайтом..."
          python scripts/sync_reports_to_site.py
      
      - name: 📊 Generate site metrics
        run: |
          echo "📊 Генерируем метрики сайта..."
          
          # Создаём файл с метриками для главной страницы
          python -c "
          import json
          import datetime
          
          # Загружаем отчёты
          with open('test_reports/simple-test-report.json', 'r') as f:
              test_data = json.load(f)
          with open('test_reports/technical-debt.json', 'r') as f:
              debt_data = json.load(f)
          
          # Создаём сводные метрики
          metrics = {
              'last_update': datetime.datetime.now().isoformat(),
              'test_success_rate': test_data.get('summary', {}).get('success_rate', 0),
              'total_tests': test_data.get('summary', {}).get('total', 0),
              'code_smells': debt_data.get('metrics', {}).get('code_smells', 0),
              'coverage': debt_data.get('metrics', {}).get('coverage', 0),
              'maintainability_rating': debt_data.get('metrics', {}).get('maintainability_rating', 'Unknown'),
              'debt_ratio': debt_data.get('metrics', {}).get('debt_ratio', 0)
          }
          
          with open('site/reports/metrics.json', 'w') as f:
              json.dump(metrics, f, indent=2)
          
          print('✅ Метрики сохранены в site/reports/metrics.json')
          "
      
      - name: 🏗️ Build site
        run: |
          echo "🏗️ Собираем сайт с обновлёнными отчётами..."
          
          # Обновляем конфигурацию MkDocs с новыми отчётами
          if [ -f "mkdocs.yml" ]; then
            echo "📝 Обновляем конфигурацию MkDocs..."
            # Добавляем страницы отчётов в навигацию если их нет
            if ! grep -q "reports/" mkdocs.yml; then
              echo "  - '🧪 Отчёты качества': reports/index.html" >> mkdocs.yml
            fi
          fi
          
          # Создаём README для директории отчётов
          cat > site/reports/README.md << 'EOF'
          # 📊 Отчёты качества кода
          
          Эта директория содержит автоматически генерируемые отчёты о качестве кода проекта JXCT.
          
          ## Файлы
          
          - `index.html` - Главная страница отчётов
          - `dashboard.html` - Краткий дашборд
          - `test-summary.json` - JSON отчёт тестирования
          - `technical-debt.json` - JSON отчёт технического долга
          - `metrics.json` - Сводные метрики для интеграции
          
          ## Автоматическое обновление
          
          Отчёты обновляются автоматически при каждом запуске CI/CD pipeline.
          EOF
      
      - name: 📝 Update main page with report links
        run: |
          echo "📝 Обновляем главную страницу сайта..."
          
          # Добавляем ссылки на отчёты в главную страницу если их нет
          if [ -f "site/index.html" ]; then
            # Проверяем, есть ли уже ссылки на отчёты
            if ! grep -q "reports/" site/index.html; then
              echo "➕ Добавляем ссылки на отчёты в главную страницу..."
              
              # Создаём временный файл с обновлённой навигацией
              python -c "
              import re
              
              with open('site/index.html', 'r', encoding='utf-8') as f:
                  content = f.read()
              
              # Ищем секцию навигации и добавляем ссылку на отчёты
              nav_pattern = r'(<div class=\"nav\"[^>]*>.*?)(</div>)'
              if re.search(nav_pattern, content, re.DOTALL):
                  # Добавляем ссылку на отчёты в навигацию
                  content = re.sub(
                      r'(<a href=\"[^\"]*\">.*?</a>)(\s*</div>)',
                      r'\1\n            <a href=\"reports/\">🧪 Отчёты качества</a>\2',
                      content,
                      flags=re.DOTALL
                  )
                  
                  with open('site/index.html', 'w', encoding='utf-8') as f:
                      f.write(content)
                  
                  print('✅ Ссылка на отчёты добавлена в главную страницу')
              else:
                  print('⚠️ Не удалось найти секцию навигации')
              "
            fi
          fi
      
      - name: 🔗 Create report widgets
        run: |
          echo "🔗 Создаём виджеты отчётов..."
          
          # Создаём JavaScript виджет для встраивания метрик
          cat > site/reports/widget.js << 'EOF'
          // Виджет отчётов JXCT
          (function() {
              const JXCT_REPORTS_API = '/reports/metrics.json';
              
              function loadReportsWidget(containerId) {
                  fetch(JXCT_REPORTS_API)
                      .then(response => response.json())
                      .then(data => {
                          const container = document.getElementById(containerId);
                          if (!container) return;
                          
                          const successRate = data.test_success_rate || 0;
                          const statusIcon = successRate >= 90 ? '✅' : successRate >= 70 ? '⚠️' : '❌';
                          const statusColor = successRate >= 90 ? '#28a745' : successRate >= 70 ? '#ffc107' : '#dc3545';
                          
                          container.innerHTML = `
                              <div style="
                                  background: white;
                                  border-radius: 8px;
                                  padding: 15px;
                                  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                                  font-family: 'Segoe UI', sans-serif;
                                  max-width: 300px;
                              ">
                                  <div style="text-align: center; margin-bottom: 10px;">
                                      <span style="font-size: 2em;">${statusIcon}</span>
                                      <div style="font-weight: bold; color: ${statusColor};">
                                          ${successRate.toFixed(1)}% тестов прошло
                                      </div>
                                  </div>
                                  <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px; font-size: 0.9em;">
                                      <div style="text-align: center;">
                                          <div style="font-weight: bold; color: #495057;">${data.total_tests || 0}</div>
                                          <div style="color: #6c757d;">Тестов</div>
                                      </div>
                                      <div style="text-align: center;">
                                          <div style="font-weight: bold; color: #495057;">${data.code_smells || 0}</div>
                                          <div style="color: #6c757d;">Code Smells</div>
                                      </div>
                                  </div>
                                  <div style="text-align: center; margin-top: 10px;">
                                      <a href="/reports/" style="
                                          display: inline-block;
                                          padding: 5px 15px;
                                          background: #2e7d32;
                                          color: white;
                                          text-decoration: none;
                                          border-radius: 4px;
                                          font-size: 0.85em;
                                      ">📊 Подробнее</a>
                                  </div>
                              </div>
                          `;
                      })
                      .catch(error => {
                          console.error('Ошибка загрузки отчётов JXCT:', error);
                          const container = document.getElementById(containerId);
                          if (container) {
                              container.innerHTML = '<div style="color: #dc3545;">Ошибка загрузки отчётов</div>';
                          }
                      });
              }
              
              // Автоматическая загрузка при готовности DOM
              if (document.readyState === 'loading') {
                  document.addEventListener('DOMContentLoaded', () => {
                      const widget = document.getElementById('jxct-reports-widget');
                      if (widget) loadReportsWidget('jxct-reports-widget');
                  });
              } else {
                  const widget = document.getElementById('jxct-reports-widget');
                  if (widget) loadReportsWidget('jxct-reports-widget');
              }
              
              // Экспортируем функцию для ручного использования
              window.loadJXCTReportsWidget = loadReportsWidget;
          })();
          EOF
          
          echo "✅ Виджет отчётов создан"
      
      - name: 💾 Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add site/reports/
          
          # Проверяем, есть ли изменения для коммита
          if git diff --staged --quiet; then
            echo "📝 Нет изменений для коммита"
          else
            git commit -m "🔄 Автоматическое обновление отчётов качества кода
            
            - Обновлены JSON отчёты тестирования
            - Перегенерированы HTML страницы отчётов
            - Обновлены метрики качества кода
            - Создан виджет для встраивания метрик
            
            Время обновления: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            
            git push
            echo "✅ Изменения отправлены в репозиторий"
          fi
      
      - name: 📊 Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          commit_message: "🚀 Обновление сайта с новыми отчётами"
      
      - name: 📈 Summary
        run: |
          echo "## 📊 Результаты обновления отчётов" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "site/reports/metrics.json" ]; then
            echo "### 🎯 Текущие метрики" >> $GITHUB_STEP_SUMMARY
            python -c "
            import json
            with open('site/reports/metrics.json', 'r') as f:
                metrics = json.load(f)
            
            success_rate = metrics.get('test_success_rate', 0)
            status_icon = '✅' if success_rate >= 90 else '⚠️' if success_rate >= 70 else '❌'
            
            print(f'- {status_icon} **Успешность тестов:** {success_rate:.1f}%')
            print(f'- 📝 **Всего тестов:** {metrics.get(\"total_tests\", 0)}')
            print(f'- 🔍 **Code Smells:** {metrics.get(\"code_smells\", 0)}')
            print(f'- 📊 **Покрытие кода:** {metrics.get(\"coverage\", 0):.1f}%')
            print(f'- 🏆 **Рейтинг:** {metrics.get(\"maintainability_rating\", \"Unknown\")}')
            " >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔗 Ссылки" >> $GITHUB_STEP_SUMMARY
          echo "- [📊 Отчёты качества](https://gfermoto.github.io/soil-sensor-7in1/reports/)" >> $GITHUB_STEP_SUMMARY
          echo "- [📈 Дашборд](https://gfermoto.github.io/soil-sensor-7in1/reports/dashboard.html)" >> $GITHUB_STEP_SUMMARY
          echo "- [📄 JSON API](https://gfermoto.github.io/soil-sensor-7in1/reports/metrics.json)" >> $GITHUB_STEP_SUMMARY
          
          echo "✅ Отчёты успешно обновлены и опубликованы!" 